{
 "title": "FastAPI Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições por Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"fastapi\"}[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Latência das Requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"fastapi\"}[5m]) / rate(http_request_duration_seconds_count{job=\"fastapi\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Erros por Rota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint, error_type) (rate(http_errors_total{job=\"fastapi\"}[5m]))",
     "legendFormat": "{{endpoint}} - {{error_type}}"
    }
   ]
  }
 ]
}